# Generated by Django 2.1.2 on 2018-10-27 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181027_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 20, 6, 16, 997150, tzinfo=utc)),
        ),
    ]
