# Generated by Django 2.1.2 on 2018-10-27 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181027_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='detailedingredient',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 20, 30, 38, 474311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.TextField(),
        ),
    ]
